name: pertouch
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.3.1=py312h06a4308_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h5d8c7f2_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - aria2=1.37.0=h4e1c2bf_3
  - arrow-cpp=19.0.0=h16717c6_5
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h4d13e43_1
  - aws-c-http=0.10.4=hbd4fbc6_1
  - aws-c-io=0.21.4=h88603f0_1
  - aws-c-mqtt=0.13.3=h680d5b3_4
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.12.12=py312hd8ed1ab_2
  - datasets=4.0.0=pyhcf101f3_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312h447239a_0
  - fsspec=2025.3.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gflags=2.2.2=h5888daf_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - glog=0.5.0=h48cff8f_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=py312he0d80d8_0
  - hdf5=1.14.5=h2b7332f_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - joblib=1.5.3=py312h06a4308_0
  - keras=3.11.2=py312h1d409f2_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcurl=8.18.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_6
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h69a702a_6
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.2.0=h767d61c_6
  - libgrpc=1.71.0=he753a82_0
  - libiconv=1.18=h3b78370_2
  - libkrb5=1.21.3=h520c7b4_4
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libprotobuf=5.29.3=h501fc15_0
  - libre2-11=2024.07.02=hba17884_3
  - libsentencepiece=0.2.0=h647b5c1_4
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_6
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h362ad58_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2cb61b6_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=py312h06a4308_1
  - mdurl=0.1.2=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - ml_dtypes=0.5.1=py312hc74f9fe_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py312hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - multidict=6.7.0=py312h8a5da7c_0
  - multiprocess=0.70.16=py312h66e93f0_1
  - namex=0.1.0=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - numexpr=2.11.0=py312hf4471f9_0
  - numpy-base=2.0.1=py312h0da6c21_1
  - openssl=3.6.1=h35e630c_1
  - optree=0.14.1=py312hdb19cb5_0
  - orc=2.1.1=hd396ef6_0
  - pandas=2.3.2=py312h277b779_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - propcache=0.3.1=py312h178313f_0
  - psutil=7.2.1=py312h5253ce2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=19.0.0=py312h7934f7d_2
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py312h868fb18_1
  - pygments=2.19.2=py312h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h0d868a3_1
  - python_abi=3.12=3_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - re2=2024.07.02=h9925aae_3
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.5.25=h5ac9029_1
  - scikit-learn=1.7.1=py312hc74f9fe_0
  - scipy=1.16.0=py312h0cc6016_0
  - sentencepiece=0.2.0=h06a4308_4
  - sentencepiece-python=0.2.0=py312hdb19cb5_4
  - sentencepiece-spm=0.2.0=hdb19cb5_4
  - sentry-sdk=2.50.0=pyhd8ed1ab_0
  - setproctitle=1.3.7=py312h5253ce2_0
  - setuptools=80.9.0=py312h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h0157908_18
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312h7040dfc_1
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer-slim=0.21.1=pyhcf101f3_0
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - wandb=0.23.1=py312h2dd4075_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py312h8a5da7c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - antlr4-python3-runtime==4.9.3
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - black==24.2.0
      - bleach==6.3.0
      - brotli==1.2.0
      - cffi==2.0.0
      - cfgv==3.5.0
      - cloudpickle==3.1.2
      - colour-science==0.4.7
      - comm==0.2.3
      - contourpy==1.3.3
      - coverage==7.13.1
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - diffusers==0.36.0
      - distlib==0.4.0
      - distro==1.9.0
      - einops==0.8.1
      - executing==2.2.1
      - facexlib==0.3.0
      - fairscale==0.4.13
      - fastapi==0.128.0
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filterpy==1.4.5
      - fonttools==4.61.1
      - fqdn==1.5.1
      - ftfy==6.1.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitpython==3.1.31
      - gradio==6.4.0
      - gradio-client==2.0.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==1.3.7
      - hydra-core==1.3.2
      - icecream==2.1.10
      - identify==2.6.16
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ipycanvas==0.14.3
      - ipykernel==7.1.0
      - ipympl==0.9.8
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.13.0
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lark==1.3.1
      - lazy-loader==0.4
      - libcst==1.7.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - lmdb==1.7.5
      - lpips==0.1.4
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - moreorless==0.5.0
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - nodeenv==1.10.0
      - notebook==7.5.2
      - notebook-shim==0.2.4
      - numba==0.63.1
      - numpy==2.4.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==2.16.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.13.0.90
      - orjson==3.11.5
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==1.0.3
      - pexpect==4.9.0
      - pillow==12.1.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - pre-commit==4.5.1
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.11
      - pycparser==2.23
      - pydub==0.25.1
      - pyiqa==0.1.14.1
      - pyparsing==3.3.1
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-json-logger==4.0.0
      - python-multipart==0.0.22
      - python-rapidjson==1.23
      - pytorch-fid==0.3.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.1
      - rpds-py==0.30.0
      - ruff==0.14.14
      - ruff-api==0.1.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - sam3==0.1.0
      - scikit-image==0.26.0
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - soupsieve==2.8.2
      - stack-data==0.6.3
      - starlette==0.50.0
      - stdlibs==2025.10.28
      - submitit==1.5.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - terminado==0.18.1
      - tifffile==2026.1.14
      - timm==1.0.24
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchmetrics==1.8.2
      - torchvision==0.21.0
      - tornado==6.5.4
      - trailrunner==1.4.0
      - traitlets==5.14.3
      - transformers==5.0.0
      - triton==3.2.0
      - typer==0.21.1
      - ufmt==2.8.0
      - uri-template==1.3.0
      - urllib3==2.6.3
      - usort==1.0.2
      - uvicorn==0.40.0
      - virtualenv==20.36.1
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - yacs==0.1.8
      - yapf==0.43.0
      - yt-dlp==2025.12.8
      - zipp==3.23.0
      - zstandard==0.25.0
